const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const url = process.env.SUPABASE_URL || 'https://pzyfbgdcflobybkwpirp.supabase.co';
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY;
const supabase = createClient(url, serviceKey);

const ncertQuestions = [
  // ==========================================
  // CLASS 10 MATHEMATICS (NCERT Sets)
  // ==========================================
  {
    question: 'According to the Fundamental Theorem of Arithmetic, every composite number can be expressed (factorised) uniquely as a product of:',
    answer: 'Primes (apart from the order in which prime factors occur)',
    explanation: 'Every composite number can be uniquely factored into prime factors, irrespective of their arrangement (e.g., 12 = 2² × 3).',
    subject: 'Mathematics',
    topic: 'Real Numbers',
    chapter_reference: 'Chapter 1: Real Numbers',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jemh1=1-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'If α and β are the zeros of a quadratic polynomial ax² + bx + c, what is the sum of zeros (α + β)?',
    answer: '-b / a',
    explanation: 'For any quadratic polynomial ax² + bx + c, the sum of roots α + β = -b/a, and product of roots αβ = c/a.',
    subject: 'Mathematics',
    topic: 'Polynomials',
    chapter_reference: 'Chapter 2: Polynomials',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jemh1=2-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'For a pair of linear equations a₁x + b₁y + c₁ = 0 and a₂x + b₂y + c₂ = 0, the system has infinitely many solutions (coincident lines) if:',
    answer: 'a₁/a₂ = b₁/b₂ = c₁/c₂',
    explanation: 'When ratios of coefficients and constants are equal (a₁/a₂ = b₁/b₂ = c₁/c₂), the lines are coincident and have infinitely many solutions.',
    subject: 'Mathematics',
    topic: 'Pair of Linear Equations',
    chapter_reference: 'Chapter 3: Linear Equations in Two Variables',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jemh1=3-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'For a quadratic equation ax² + bx + c = 0, what is the condition for two distinct real roots?',
    answer: 'b² - 4ac > 0 (Discriminant is strictly positive)',
    explanation: 'If discriminant D = b² - 4ac > 0, roots are real and distinct; if D = 0, roots are real and equal; if D < 0, no real roots exist.',
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    chapter_reference: 'Chapter 4: Quadratic Equations',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jemh1=4-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the formula for the nth term (aₙ) of an Arithmetic Progression with first term a and common difference d?',
    answer: 'aₙ = a + (n - 1)d',
    explanation: 'The nth term of an AP is given by aₙ = a + (n - 1)d, where a is the first term and d is the common difference.',
    subject: 'Mathematics',
    topic: 'Arithmetic Progressions',
    chapter_reference: 'Chapter 5: Arithmetic Progressions',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jemh1=5-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the sum Sₙ of the first n terms of an Arithmetic Progression?',
    answer: 'Sₙ = (n/2)[2a + (n - 1)d]',
    explanation: 'The sum of n terms is (n/2) times the sum of first term and last term: Sₙ = n/2 * (2a + (n-1)d).',
    subject: 'Mathematics',
    topic: 'Arithmetic Progressions',
    chapter_reference: 'Chapter 5: Arithmetic Progressions',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jemh1=5-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'State the Basic Proportionality Theorem (Thales Theorem).',
    answer: 'If a line is drawn parallel to one side of a triangle intersecting other two sides, it divides them in the same ratio.',
    explanation: 'In △ABC, if DE ∥ BC intersecting AB at D and AC at E, then AD/DB = AE/EC.',
    subject: 'Mathematics',
    topic: 'Triangles',
    chapter_reference: 'Chapter 6: Triangles',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jemh1=6-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the distance between two points P(x₁, y₁) and Q(x₂, y₂)?',
    answer: 'd = √[(x₂ - x₁)² + (y₂ - y₁)²]',
    explanation: 'Using the Pythagorean theorem in the coordinate plane, the distance formula is √[(x₂ - x₁)² + (y₂ - y₁)²].',
    subject: 'Mathematics',
    topic: 'Coordinate Geometry',
    chapter_reference: 'Chapter 7: Coordinate Geometry',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jemh1=7-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the fundamental trigonometric identity relating sin θ and cos θ for any acute angle θ?',
    answer: 'sin² θ + cos² θ = 1',
    explanation: 'From the right triangle definition, (opposite/hypotenuse)² + (adjacent/hypotenuse)² = (opposite² + adjacent²)/hypotenuse² = hypotenuse²/hypotenuse² = 1.',
    subject: 'Mathematics',
    topic: 'Introduction to Trigonometry',
    chapter_reference: 'Chapter 8: Introduction to Trigonometry',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jemh1=8-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the value of tan 45° and sin 30°?',
    answer: 'tan 45° = 1 and sin 30° = 1/2',
    explanation: 'From standard trigonometric tables: tan 45° = 1, sin 30° = 1/2, cos 60° = 1/2, and sin 90° = 1.',
    subject: 'Mathematics',
    topic: 'Introduction to Trigonometry',
    chapter_reference: 'Chapter 8: Introduction to Trigonometry',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jemh1=8-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the angle between a tangent to a circle and the radius drawn through the point of contact?',
    answer: '90 degrees (perpendicular)',
    explanation: 'Theorem 10.1: The tangent at any point of a circle is perpendicular to the radius through the point of contact.',
    subject: 'Mathematics',
    topic: 'Circles',
    chapter_reference: 'Chapter 10: Circles',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jemh1=10-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the empirical relationship between Mean, Median, and Mode in statistics?',
    answer: '3 Median = Mode + 2 Mean',
    explanation: 'For a moderately skewed frequency distribution, Karl Pearson’s empirical formula is: Mode = 3 Median - 2 Mean.',
    subject: 'Mathematics',
    topic: 'Statistics',
    chapter_reference: 'Chapter 14: Statistics',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?jemh1=14-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'If P(E) is the probability of an event E happening, what is the value of P(E) + P(not E)?',
    answer: '1',
    explanation: 'The sum of the probabilities of all elementary events of an experiment is 1, so P(E) + P(E̅) = 1.',
    subject: 'Mathematics',
    topic: 'Probability',
    chapter_reference: 'Chapter 15: Probability',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jemh1=15-15 (NCERT Class 10 Maths)',
  },

  // ==========================================
  // CLASS 10 SCIENCE - PHYSICS (NCERT Sets)
  // ==========================================
  {
    question: 'What is the mirror formula relating object distance (u), image distance (v), and focal length (f)?',
    answer: '1/f = 1/v + 1/u',
    explanation: 'The mirror formula 1/f = 1/v + 1/u holds true for all spherical mirrors in all positions of the object using Cartesian sign convention.',
    subject: 'Physics',
    topic: 'Light - Reflection and Refraction',
    chapter_reference: 'Chapter 10: Light - Reflection and Refraction',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=10-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is the lens formula relating object distance (u), image distance (v), and focal length (f)?',
    answer: '1/f = 1/v - 1/u',
    explanation: 'For thin spherical lenses, 1/f = 1/v - 1/u. Note the negative sign distinguishing it from the mirror formula.',
    subject: 'Physics',
    topic: 'Light - Reflection and Refraction',
    chapter_reference: 'Chapter 10: Light - Reflection and Refraction',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=10-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is the SI unit of power of a lens?',
    answer: 'Dioptre (D)',
    explanation: 'Power of a lens P = 1/f (in meters). 1 Dioptre is the power of a lens of focal length 1 metre.',
    subject: 'Physics',
    topic: 'Light - Reflection and Refraction',
    chapter_reference: 'Chapter 10: Light - Reflection and Refraction',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=10-16 (NCERT Class 10 Science)',
  },
  {
    question: 'Which defect of vision is corrected using a concave lens?',
    answer: 'Myopia (Short-sightedness)',
    explanation: 'In myopia, the image is formed in front of the retina. A diverging (concave) lens with appropriate power brings the image back onto the retina.',
    subject: 'Physics',
    topic: 'The Human Eye and Colourful World',
    chapter_reference: 'Chapter 11: The Human Eye and the Colourful World',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=11-16 (NCERT Class 10 Science)',
  },
  {
    question: 'Why does the sky appear blue on a clear day?',
    answer: 'Rayleigh scattering of light (shorter blue wavelengths scatter more by atmospheric molecules)',
    explanation: 'Fine particles in the air scatter blue light (shorter wavelength) more strongly than red light (longer wavelength), causing the blue appearance.',
    subject: 'Physics',
    topic: 'Atmospheric Refraction & Scattering',
    chapter_reference: 'Chapter 11: The Human Eye and the Colourful World',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jesc1=11-16 (NCERT Class 10 Science)',
  },
  {
    question: 'State Ohm’s Law mathematically for a metallic conductor at constant temperature.',
    answer: 'V = I × R (Potential difference is directly proportional to current)',
    explanation: 'Ohm’s law states V ∝ I at constant physical conditions, giving V = IR where R is the resistance of the conductor.',
    subject: 'Physics',
    topic: 'Electricity',
    chapter_reference: 'Chapter 12: Electricity',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=12-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is Joule’s Law of Heating expression for heat produced (H) by current I through resistance R in time t?',
    answer: 'H = I²Rt',
    explanation: 'Heat produced in a resistor is directly proportional to the square of current (I²), resistance (R), and time (t): H = I²Rt.',
    subject: 'Physics',
    topic: 'Heating Effect of Current',
    chapter_reference: 'Chapter 12: Electricity',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=12-16 (NCERT Class 10 Science)',
  },
  {
    question: 'According to Fleming’s Left-Hand Rule, what do the thumb, forefinger, and middle finger represent?',
    answer: 'Thumb: Motion/Force, Forefinger: Magnetic Field, Middle finger: Current (FBI rule)',
    explanation: 'When stretched perpendicularly, Forefinger = Field, Middle finger = Current, Thumb = Force/Motion direction on the conductor.',
    subject: 'Physics',
    topic: 'Magnetic Effects of Electric Current',
    chapter_reference: 'Chapter 13: Magnetic Effects of Electric Current',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=13-16 (NCERT Class 10 Science)',
  },

  // ==========================================
  // CLASS 10 SCIENCE - CHEMISTRY (NCERT Sets)
  // ==========================================
  {
    question: 'What is the chemical formula of Plaster of Paris?',
    answer: 'CaSO₄ · ½H₂O (Calcium sulphate hemihydrate)',
    explanation: 'On heating Gypsum (CaSO₄ · 2H₂O) at 373 K, it loses water molecules and becomes Plaster of Paris (CaSO₄ · ½H₂O).',
    subject: 'Chemistry',
    topic: 'Acids, Bases and Salts',
    chapter_reference: 'Chapter 2: Acids, Bases and Salts',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=2-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is the chemical name and formula of Baking Soda?',
    answer: 'Sodium hydrogen carbonate (NaHCO₃)',
    explanation: 'Baking soda is NaHCO₃, produced using sodium chloride in the Solvay process: NaCl + H₂O + CO₂ + NH₃ → NH₄Cl + NaHCO₃.',
    subject: 'Chemistry',
    topic: 'Acids, Bases and Salts',
    chapter_reference: 'Chapter 2: Acids, Bases and Salts',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=2-16 (NCERT Class 10 Science)',
  },
  {
    question: 'Which metal exists in liquid state at room temperature?',
    answer: 'Mercury (Hg)',
    explanation: 'Mercury is the only metallic element that is liquid at standard room temperature and pressure.',
    subject: 'Chemistry',
    topic: 'Metals and Non-metals',
    chapter_reference: 'Chapter 3: Metals and Non-metals',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=3-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is an amphoteric oxide? Give an example.',
    answer: 'Oxides that react with both acids and bases to produce salt and water (e.g., Al₂O₃, ZnO)',
    explanation: 'Aluminium oxide (Al₂O₃) and Zinc oxide (ZnO) show both acidic and basic behavior, neutralizing both acids and bases.',
    subject: 'Chemistry',
    topic: 'Metals and Non-metals',
    chapter_reference: 'Chapter 3: Metals and Non-metals',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jesc1=3-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What unique property allows carbon to form long chains with other carbon atoms?',
    answer: 'Catenation and Tetravalency',
    explanation: 'Catenation is the unique ability of carbon to form bonds with other carbon atoms, creating extensive branched, cyclic, or linear chains.',
    subject: 'Chemistry',
    topic: 'Carbon and its Compounds',
    chapter_reference: 'Chapter 4: Carbon and its Compounds',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=4-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is the general molecular formula for Alkanes (saturated hydrocarbons)?',
    answer: 'CₙH₂ₙ₊₂',
    explanation: 'Alkanes have single covalent bonds between carbons and follow CₙH₂ₙ₊₂ (Methane CH₄, Ethane C₂H₆, Propane C₃H₈).',
    subject: 'Chemistry',
    topic: 'Carbon and its Compounds',
    chapter_reference: 'Chapter 4: Carbon and its Compounds',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=4-16 (NCERT Class 10 Science)',
  },

  // ==========================================
  // CLASS 10 SCIENCE - BIOLOGY (NCERT Sets)
  // ==========================================
  {
    question: 'What is the basic functional filtration unit of the human kidney called?',
    answer: 'Nephron',
    explanation: 'Each kidney contains approximately 1 million nephrons, consisting of Bowman’s capsule and glomerulus for blood filtration.',
    subject: 'Biology',
    topic: 'Life Processes - Excretion',
    chapter_reference: 'Chapter 6: Life Processes',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=6-16 (NCERT Class 10 Science)',
  },
  {
    question: 'Which enzyme present in saliva breaks down complex starch into simple sugars?',
    answer: 'Salivary Amylase (Ptyalin)',
    explanation: 'Saliva contains salivary amylase, which hydrolyzes starch into maltose at an optimum pH of around 6.8.',
    subject: 'Biology',
    topic: 'Life Processes - Nutrition',
    chapter_reference: 'Chapter 6: Life Processes',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=6-16 (NCERT Class 10 Science)',
  },
  {
    question: 'Which plant hormone is responsible for the ripening of fruits and promotion of senescence?',
    answer: 'Ethylene',
    explanation: 'Ethylene is a gaseous phytohormone that promotes fruit ripening, while Auxins promote cell elongation and Abscisic acid causes stomata closure.',
    subject: 'Biology',
    topic: 'Control and Coordination',
    chapter_reference: 'Chapter 7: Control and Coordination',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?jesc1=7-16 (NCERT Class 10 Science)',
  },
  {
    question: 'In Mendel’s dihybrid cross, what is the phenotypic ratio in the F₂ generation?',
    answer: '9 : 3 : 3 : 1',
    explanation: 'Crossing round-yellow with wrinkled-green seeds gives a 9 (Round Yellow) : 3 (Round Green) : 3 (Wrinkled Yellow) : 1 (Wrinkled Green) phenotypic ratio.',
    subject: 'Biology',
    topic: 'Heredity and Evolution',
    chapter_reference: 'Chapter 9: Heredity and Evolution',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=9-16 (NCERT Class 10 Science)',
  },
  {
    question: 'According to Lindeman’s 10% law of energy transfer in an ecosystem, how much energy is transferred from one trophic level to the next?',
    answer: 'Only 10% of energy is transferred to the next trophic level',
    explanation: 'Roughly 90% of energy is lost as metabolic heat, respiration, and waste at each level; only 10% becomes biomass for the next consumer.',
    subject: 'Biology',
    topic: 'Our Environment',
    chapter_reference: 'Chapter 15: Our Environment',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=15-16 (NCERT Class 10 Science)',
  },

  // ==========================================
  // CLASS 9 NCERT CURRICULUM QUESTIONS
  // ==========================================
  {
    question: 'What is the value of Universal Gravitational Constant (G)?',
    answer: '6.674 × 10⁻¹¹ N·m²/kg²',
    explanation: 'Discovered by Henry Cavendish, G = 6.674 × 10⁻¹¹ N·m²/kg² is a fundamental constant in Newton’s Law of Universal Gravitation.',
    subject: 'Physics',
    topic: 'Gravitation',
    chapter_reference: 'Chapter 10: Gravitation',
    curriculum: 'NCERT',
    class_level: 9,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?iesc1=10-15 (NCERT Class 9 Science)',
  },
  {
    question: 'State Newton’s First Law of Motion (Law of Inertia).',
    answer: 'An object remains in a state of rest or uniform motion unless compelled to change that state by an external unbalanced force.',
    explanation: 'Newton’s first law defines inertia, the inherent tendency of objects to resist any change in their velocity.',
    subject: 'Physics',
    topic: 'Force and Laws of Motion',
    chapter_reference: 'Chapter 9: Force and Laws of Motion',
    curriculum: 'NCERT',
    class_level: 9,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?iesc1=9-15 (NCERT Class 9 Science)',
  },
  {
    question: 'What is the difference between speed and velocity?',
    answer: 'Speed is a scalar quantity (magnitude only), while velocity is a vector quantity (magnitude and direction).',
    explanation: 'Velocity specifies how fast an object moves and in which direction (v = displacement / time).',
    subject: 'Physics',
    topic: 'Motion',
    chapter_reference: 'Chapter 8: Motion',
    curriculum: 'NCERT',
    class_level: 9,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?iesc1=8-15 (NCERT Class 9 Science)',
  },
  {
    question: 'State the Law of Conservation of Mass proposed by Antoine Lavoisier.',
    answer: 'Mass can neither be created nor destroyed in a chemical reaction.',
    explanation: 'Total mass of reactants equals the total mass of products in any closed chemical reaction.',
    subject: 'Chemistry',
    topic: 'Atoms and Molecules',
    chapter_reference: 'Chapter 3: Atoms and Molecules',
    curriculum: 'NCERT',
    class_level: 9,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?iesc1=3-15 (NCERT Class 9 Science)',
  },
  // ==========================================
  // CLASS 11 MATHEMATICS (NCERT Sets)
  // ==========================================
  {
    question: 'Let A and B be two sets such that n(A) = 5 and n(B) = 6. If n(A ∩ B) = 3, what is n(A ∪ B)?',
    answer: '8',
    explanation: 'Using the formula n(A ∪ B) = n(A) + n(B) - n(A ∩ B), we get n(A ∪ B) = 5 + 6 - 3 = 8.',
    subject: 'Mathematics',
    topic: 'Sets',
    chapter_reference: 'Chapter 1: Sets',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.95,
    source: 'https://ncert.nic.in/textbook.php?jemh1=1-15 (NCERT Class 11 Maths)',
  },
  {
    question: 'Find the domain of the function f(x) = √(x - 2).',
    answer: '[2, ∞)',
    explanation: 'For the square root function to be defined, the expression inside must be non-negative: x - 2 ≥ 0, which gives x ≥ 2.',
    subject: 'Mathematics',
    topic: 'Relations and Functions',
    chapter_reference: 'Chapter 2: Relations and Functions',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?jemh1=2-15 (NCERT Class 11 Maths)',
  },
  {
    question: 'Convert 40° into radians.',
    answer: '2π/9 radians',
    explanation: 'To convert degrees to radians, multiply by π/180: 40° × π/180 = 40π/180 = 2π/9 radians.',
    subject: 'Mathematics',
    topic: 'Trigonometric Functions',
    chapter_reference: 'Chapter 3: Trigonometric Functions',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.94,
    source: 'https://ncert.nic.in/textbook.php?jemh1=3-15 (NCERT Class 11 Maths)',
  },
  // ==========================================
  // CLASS 11 PHYSICS (NCERT Sets)
  // ==========================================
  {
    question: 'What is the SI unit of pressure?',
    answer: 'Pascal (Pa)',
    explanation: 'Pressure is defined as force per unit area. The SI unit of force is newton (N) and area is square meter (m²), so pressure has unit N/m² which is called pascal (Pa).',
    subject: 'Physics',
    topic: 'Units and Measurements',
    chapter_reference: 'Chapter 2: Units and Measurements',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?iesc1=2-15 (NCERT Class 11 Physics)',
  },
  {
    question: 'A body travels half its total path in the last second of its fall from rest. Find the total time of fall.',
    answer: '3.414 s',
    explanation: 'Using equations of motion: s = gt²/2 for total distance and s/2 = g(t - 1)²/2 for distance in (t-1) seconds. Solving gives t = 2 + √2 ≈ 3.414 seconds.',
    subject: 'Physics',
    topic: 'Motion in a Straight Line',
    chapter_reference: 'Chapter 3: Motion in a Straight Line',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'hard',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?iesc1=3-15 (NCERT Class 11 Physics)',
  },
  {
    question: 'What is the work done by a force in displacing a body when the force acts at an angle of 90° to the direction of displacement?',
    answer: 'Zero',
    explanation: 'Work done W = F·d·cosθ. When θ = 90°, cos 90° = 0, therefore W = F·d·0 = 0.',
    subject: 'Physics',
    topic: 'Work, Energy and Power',
    chapter_reference: 'Chapter 6: Work, Energy and Power',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?iesc1=6-15 (NCERT Class 11 Physics)',
  },
  // ==========================================
  // CLASS 11 CHEMISTRY (NCERT Sets)
  // ==========================================
  {
    question: 'What is the number of significant figures in 0.002500?',
    answer: '4',
    explanation: 'Leading zeros are not significant. Trailing zeros after a decimal point are significant. So in 0.002500, the significant digits are 2, 5, 0, 0 which gives 4 significant figures.',
    subject: 'Chemistry',
    topic: 'Some Basic Concepts of Chemistry',
    chapter_reference: 'Chapter 1: Some Basic Concepts of Chemistry',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.95,
    source: 'https://ncert.nic.in/textbook.php?iesc1=1-15 (NCERT Class 11 Chemistry)',
  },
  {
    question: 'What is the azimuthal quantum number (l) for an electron in a 3p orbital?',
    answer: '1',
    explanation: 'For p orbitals, the azimuthal quantum number l = 1. The principal quantum number n = 3 for 3p orbital.',
    subject: 'Chemistry',
    topic: 'Structure of Atom',
    chapter_reference: 'Chapter 2: Structure of Atom',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'medium',
    quality_score: 0.94,
    source: 'https://ncert.nic.in/textbook.php?iesc1=2-15 (NCERT Class 11 Chemistry)',
  },
  {
    question: 'Which of the following has the largest bond angle? H₂O, NH₃, CH₄',
    answer: 'CH₄',
    explanation: 'CH₄ has tetrahedral geometry with bond angle 109.5°. NH₃ has trigonal pyramidal geometry with bond angle 107° due to lone pair-bond pair repulsion. H₂O has bent geometry with bond angle 104.5° due to two lone pairs.',
    subject: 'Chemistry',
    topic: 'Chemical Bonding and Molecular Structure',
    chapter_reference: 'Chapter 4: Chemical Bonding and Molecular Structure',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'medium',
    quality_score: 0.93,
    source: 'https://ncert.nic.in/textbook.php?iesc1=4-15 (NCERT Class 11 Chemistry)',
  },
  // ==========================================
  // CLASS 11 BIOLOGY (NCERT Sets)
  // ==========================================
  {
    question: 'Which of the following is not a characteristic of living organisms?',
    answer: 'Isolation',
    explanation: 'Living organisms show growth, reproduction, metabolism, response to stimuli, etc. Isolation is not a biological characteristic; in fact, organisms interact with their environment and other organisms.',
    subject: 'Biology',
    topic: 'The Living World',
    chapter_reference: 'Chapter 1: The Living World',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?iesc1=1-15 (NCERT Class 11 Biology)',
  },
  {
    question: 'What is the function of the ribosome in a cell?',
    answer: 'Protein synthesis',
    explanation: 'Ribosomes are the site of protein synthesis in cells. They read mRNA and assemble amino acids into polypeptide chains.',
    subject: 'Biology',
    topic: 'Cell: The Unit of Life',
    chapter_reference: 'Chapter 8: Cell: The Unit of Life',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?iesc1=8-15 (NCERT Class 11 Biology)',
  },
  {
    question: 'During which phase of mitosis do chromosomes align at the equatorial plate?',
    answer: 'Metaphase',
    explanation: 'In metaphase of mitosis, chromosomes line up along the metaphase plate (equatorial plane) of the cell, attached to spindle fibers from opposite poles.',
    subject: 'Biology',
    topic: 'Cell Cycle and Cell Division',
    chapter_reference: 'Chapter 10: Cell Cycle and Cell Division',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'medium',
    quality_score: 0.95,
    source: 'https://ncert.nic.in/textbook.php?iesc1=10-15 (NCERT Class 11 Biology)',
  },
  {
    question: 'Which enzyme is responsible for carbon fixation in C3 plants?',
    answer: 'RuBisCO (Ribulose-1,5-bisphosphate carboxylase-oxygenase)',
    explanation: 'RuBisCO catalyzes the first major step of carbon fixation in the Calvin cycle (C3 pathway), combining CO2 with ribulose 1,5-bisphosphate.',
    subject: 'Biology',
    topic: 'Photosynthesis in Higher Plants',
    chapter_reference: 'Chapter 13: Photosynthesis in Higher Plants',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?iesc1=13-15 (NCERT Class 11 Biology)',
  },
  {
    question: 'What is the end product of glycolysis under aerobic conditions?',
    answer: 'Pyruvic acid (Pyruvate)',
    explanation: 'In glycolysis, one molecule of glucose is cleaved through 10 enzymatic reactions to yield two molecules of pyruvic acid, along with 2 ATP and 2 NADH.',
    subject: 'Biology',
    topic: 'Respiration in Plants',
    chapter_reference: 'Chapter 14: Respiration in Plants',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'medium',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?iesc1=14-15 (NCERT Class 11 Biology)',
  },
  {
    question: 'Which plant hormone is primarily responsible for apical dominance?',
    answer: 'Auxin (Indole-3-acetic acid)',
    explanation: 'Auxins produced at the shoot tip inhibit the growth of lateral (axillary) buds, a phenomenon called apical dominance.',
    subject: 'Biology',
    topic: 'Plant Growth and Development',
    chapter_reference: 'Chapter 15: Plant Growth and Development',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.95,
    source: 'https://ncert.nic.in/textbook.php?iesc1=15-15 (NCERT Class 11 Biology)',
  },
  // Additional Class 11 Mathematics
  {
    question: 'What is the value of i^4k + i^(4k+1) + i^(4k+2) + i^(4k+3) for any integer k?',
    answer: '0',
    explanation: 'Since i^4k = 1, i^(4k+1) = i, i^(4k+2) = -1, and i^(4k+3) = -i, their sum is 1 + i - 1 - i = 0.',
    subject: 'Mathematics',
    topic: 'Complex Numbers and Quadratic Equations',
    chapter_reference: 'Chapter 5: Complex Numbers',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'medium',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?jemh1=5-15 (NCERT Class 11 Maths)',
  },
  {
    question: 'In how many ways can 5 distinct books be arranged on a shelf?',
    answer: '120 ways',
    explanation: 'The number of permutations of 5 distinct items is 5! = 5 × 4 × 3 × 2 × 1 = 120.',
    subject: 'Mathematics',
    topic: 'Permutations and Combinations',
    chapter_reference: 'Chapter 7: Permutations and Combinations',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jemh1=7-15 (NCERT Class 11 Maths)',
  },
  {
    question: 'What is the sum of an infinite geometric progression with first term a and common ratio r (|r| < 1)?',
    answer: 'S_∞ = a / (1 - r)',
    explanation: 'For an infinite GP where |r| < 1, as n → ∞, r^n → 0, yielding the sum formula S_∞ = a / (1 - r).',
    subject: 'Mathematics',
    topic: 'Sequences and Series',
    chapter_reference: 'Chapter 9: Sequences and Series',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jemh1=9-15 (NCERT Class 11 Maths)',
  },
  {
    question: 'What is the derivative of sin(x) with respect to x from first principles?',
    answer: 'cos(x)',
    explanation: 'By the definition of derivative, lim(h→0) [sin(x + h) - sin(x)] / h = lim(h→0) [2 cos(x + h/2) sin(h/2)] / h = cos(x).',
    subject: 'Mathematics',
    topic: 'Limits and Derivatives',
    chapter_reference: 'Chapter 13: Limits and Derivatives',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'medium',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?jemh1=13-15 (NCERT Class 11 Maths)',
  },
  // Additional Class 11 Physics
  {
    question: 'What is the escape velocity of a body from the surface of the Earth?',
    answer: '11.2 km/s',
    explanation: 'Escape velocity is v_e = √(2gR) = √(2 × 9.8 × 6.4 × 10⁶) ≈ 11.2 km/s.',
    subject: 'Physics',
    topic: 'Gravitation',
    chapter_reference: 'Chapter 8: Gravitation',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?iesc1=8-15 (NCERT Class 11 Physics)',
  },
  {
    question: 'State Hooke’s Law for an elastic material within its proportional limit.',
    answer: 'Stress is directly proportional to Strain',
    explanation: 'Hooke’s Law states that within elastic limit, Stress ∝ Strain, or Stress / Strain = Modulus of Elasticity (E).',
    subject: 'Physics',
    topic: 'Mechanical Properties of Solids',
    chapter_reference: 'Chapter 9: Mechanical Properties of Solids',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?iesc1=9-15 (NCERT Class 11 Physics)',
  },
  {
    question: 'State the First Law of Thermodynamics in equation form.',
    answer: 'ΔQ = ΔU + ΔW (Heat added = Increase in internal energy + Work done)',
    explanation: 'The first law of thermodynamics is an expression of the principle of conservation of energy: ΔQ = ΔU + PΔV.',
    subject: 'Physics',
    topic: 'Thermodynamics',
    chapter_reference: 'Chapter 12: Thermodynamics',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?iesc1=12-15 (NCERT Class 11 Physics)',
  },
  // Additional Class 11 Chemistry
  {
    question: 'What is the shape and bond angle of methane (CH4) according to VSEPR theory?',
    answer: 'Tetrahedral geometry with bond angle of 109.5°',
    explanation: 'Carbon in CH4 is sp3 hybridized with 4 bonding pairs and 0 lone pairs, minimizing electron repulsion in a tetrahedral geometry.',
    subject: 'Chemistry',
    topic: 'Chemical Bonding and Molecular Structure',
    chapter_reference: 'Chapter 4: Chemical Bonding',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?iesc1=4-15 (NCERT Class 11 Chemistry)',
  },
  {
    question: 'What is the conjugate acid of NH3 (ammonia)?',
    answer: 'NH4+ (Ammonium ion)',
    explanation: 'According to the Bronsted-Lowry concept, a conjugate acid is formed when a base accepts a proton (H+). NH3 + H+ → NH4+.',
    subject: 'Chemistry',
    topic: 'Equilibrium',
    chapter_reference: 'Chapter 7: Equilibrium',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'basic',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?iesc1=7-15 (NCERT Class 11 Chemistry)',
  },
  {
    question: 'What is the oxidation number of chromium in K2Cr2O7?',
    answer: '+6',
    explanation: '2(+1) + 2(Cr) + 7(-2) = 0 ⇒ 2 + 2(Cr) - 14 = 0 ⇒ 2(Cr) = 12 ⇒ Cr = +6.',
    subject: 'Chemistry',
    topic: 'Redox Reactions',
    chapter_reference: 'Chapter 8: Redox Reactions',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'medium',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?iesc1=8-15 (NCERT Class 11 Chemistry)',
  },
  {
    question: 'What type of isomerism is shown by but-1-ene and but-2-ene?',
    answer: 'Position isomerism',
    explanation: 'But-1-ene and but-2-ene have the same carbon skeleton but differ in the position of the double bond (C=C), making them position isomers.',
    subject: 'Chemistry',
    topic: 'Organic Chemistry: Some Basic Principles and Techniques',
    chapter_reference: 'Chapter 12: Organic Chemistry',
    curriculum: 'NCERT',
    class_level: 11,
    difficulty: 'medium',
    quality_score: 0.95,
    source: 'https://ncert.nic.in/textbook.php?iesc1=12-15 (NCERT Class 11 Chemistry)',
  },
];

async function seed() {
  console.log(`Checking existing questions in 'education' table...`);
  const { data: existingRows, error: fetchErr } = await supabase
    .from('education')
    .select('question');

  if (fetchErr) {
    console.error('Fetch error:', fetchErr.message);
    return;
  }

  const existingQuestionsSet = new Set((existingRows || []).map(r => r.question.trim().toLowerCase()));
  const newQuestions = ncertQuestions.filter(q => !existingQuestionsSet.has(q.question.trim().toLowerCase()));

  console.log(`Found ${existingRows?.length || 0} existing questions in DB. Inserting ${newQuestions.length} new questions...`);

  if (newQuestions.length > 0) {
    const { data: insData, error: insErr } = await supabase
      .from('education')
      .insert(newQuestions);

    if (insErr) {
      console.error('Insert error:', insErr.message);
    } else {
      console.log(`Successfully inserted ${newQuestions.length} questions into database!`);
    }
  } else {
    console.log('All questions are already present in database.');
  }

  // Verify counts by class level
  const { data: rows, error: countErr } = await supabase.from('education').select('class_level');
  if (!countErr && rows) {
    const counts = {};
    rows.forEach(r => counts[r.class_level] = (counts[r.class_level] || 0) + 1);
    console.log(`Total live questions in Supabase 'education' table now: ${rows.length}`, counts);
  }
}

seed();
