const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const url = process.env.SUPABASE_URL || 'https://pzyfbgdcflobybkwpirp.supabase.co';
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY;
const supabase = createClient(url, serviceKey);

const ncertQuestions = [
  // ==========================================
  // CLASS 10 MATHEMATICS (NCERT Sets)
  // ==========================================
  {
    question: 'According to the Fundamental Theorem of Arithmetic, every composite number can be expressed (factorised) uniquely as a product of:',
    answer: 'Primes (apart from the order in which prime factors occur)',
    explanation: 'Every composite number can be uniquely factored into prime factors, irrespective of their arrangement (e.g., 12 = 2² × 3).',
    subject: 'Mathematics',
    topic: 'Real Numbers',
    chapter_reference: 'Chapter 1: Real Numbers',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jemh1=1-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'If α and β are the zeros of a quadratic polynomial ax² + bx + c, what is the sum of zeros (α + β)?',
    answer: '-b / a',
    explanation: 'For any quadratic polynomial ax² + bx + c, the sum of roots α + β = -b/a, and product of roots αβ = c/a.',
    subject: 'Mathematics',
    topic: 'Polynomials',
    chapter_reference: 'Chapter 2: Polynomials',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jemh1=2-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'For a pair of linear equations a₁x + b₁y + c₁ = 0 and a₂x + b₂y + c₂ = 0, the system has infinitely many solutions (coincident lines) if:',
    answer: 'a₁/a₂ = b₁/b₂ = c₁/c₂',
    explanation: 'When ratios of coefficients and constants are equal (a₁/a₂ = b₁/b₂ = c₁/c₂), the lines are coincident and have infinitely many solutions.',
    subject: 'Mathematics',
    topic: 'Pair of Linear Equations',
    chapter_reference: 'Chapter 3: Linear Equations in Two Variables',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jemh1=3-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'For a quadratic equation ax² + bx + c = 0, what is the condition for two distinct real roots?',
    answer: 'b² - 4ac > 0 (Discriminant is strictly positive)',
    explanation: 'If discriminant D = b² - 4ac > 0, roots are real and distinct; if D = 0, roots are real and equal; if D < 0, no real roots exist.',
    subject: 'Mathematics',
    topic: 'Quadratic Equations',
    chapter_reference: 'Chapter 4: Quadratic Equations',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jemh1=4-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the formula for the nth term (aₙ) of an Arithmetic Progression with first term a and common difference d?',
    answer: 'aₙ = a + (n - 1)d',
    explanation: 'The nth term of an AP is given by aₙ = a + (n - 1)d, where a is the first term and d is the common difference.',
    subject: 'Mathematics',
    topic: 'Arithmetic Progressions',
    chapter_reference: 'Chapter 5: Arithmetic Progressions',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jemh1=5-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the sum Sₙ of the first n terms of an Arithmetic Progression?',
    answer: 'Sₙ = (n/2)[2a + (n - 1)d]',
    explanation: 'The sum of n terms is (n/2) times the sum of first term and last term: Sₙ = n/2 * (2a + (n-1)d).',
    subject: 'Mathematics',
    topic: 'Arithmetic Progressions',
    chapter_reference: 'Chapter 5: Arithmetic Progressions',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jemh1=5-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'State the Basic Proportionality Theorem (Thales Theorem).',
    answer: 'If a line is drawn parallel to one side of a triangle intersecting other two sides, it divides them in the same ratio.',
    explanation: 'In △ABC, if DE ∥ BC intersecting AB at D and AC at E, then AD/DB = AE/EC.',
    subject: 'Mathematics',
    topic: 'Triangles',
    chapter_reference: 'Chapter 6: Triangles',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jemh1=6-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the distance between two points P(x₁, y₁) and Q(x₂, y₂)?',
    answer: 'd = √[(x₂ - x₁)² + (y₂ - y₁)²]',
    explanation: 'Using the Pythagorean theorem in the coordinate plane, the distance formula is √[(x₂ - x₁)² + (y₂ - y₁)²].',
    subject: 'Mathematics',
    topic: 'Coordinate Geometry',
    chapter_reference: 'Chapter 7: Coordinate Geometry',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jemh1=7-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the fundamental trigonometric identity relating sin θ and cos θ for any acute angle θ?',
    answer: 'sin² θ + cos² θ = 1',
    explanation: 'From the right triangle definition, (opposite/hypotenuse)² + (adjacent/hypotenuse)² = (opposite² + adjacent²)/hypotenuse² = hypotenuse²/hypotenuse² = 1.',
    subject: 'Mathematics',
    topic: 'Introduction to Trigonometry',
    chapter_reference: 'Chapter 8: Introduction to Trigonometry',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jemh1=8-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the value of tan 45° and sin 30°?',
    answer: 'tan 45° = 1 and sin 30° = 1/2',
    explanation: 'From standard trigonometric tables: tan 45° = 1, sin 30° = 1/2, cos 60° = 1/2, and sin 90° = 1.',
    subject: 'Mathematics',
    topic: 'Introduction to Trigonometry',
    chapter_reference: 'Chapter 8: Introduction to Trigonometry',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jemh1=8-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the angle between a tangent to a circle and the radius drawn through the point of contact?',
    answer: '90 degrees (perpendicular)',
    explanation: 'Theorem 10.1: The tangent at any point of a circle is perpendicular to the radius through the point of contact.',
    subject: 'Mathematics',
    topic: 'Circles',
    chapter_reference: 'Chapter 10: Circles',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jemh1=10-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'What is the empirical relationship between Mean, Median, and Mode in statistics?',
    answer: '3 Median = Mode + 2 Mean',
    explanation: 'For a moderately skewed frequency distribution, Karl Pearson’s empirical formula is: Mode = 3 Median - 2 Mean.',
    subject: 'Mathematics',
    topic: 'Statistics',
    chapter_reference: 'Chapter 14: Statistics',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?jemh1=14-15 (NCERT Class 10 Maths)',
  },
  {
    question: 'If P(E) is the probability of an event E happening, what is the value of P(E) + P(not E)?',
    answer: '1',
    explanation: 'The sum of the probabilities of all elementary events of an experiment is 1, so P(E) + P(E̅) = 1.',
    subject: 'Mathematics',
    topic: 'Probability',
    chapter_reference: 'Chapter 15: Probability',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jemh1=15-15 (NCERT Class 10 Maths)',
  },

  // ==========================================
  // CLASS 10 SCIENCE - PHYSICS (NCERT Sets)
  // ==========================================
  {
    question: 'What is the mirror formula relating object distance (u), image distance (v), and focal length (f)?',
    answer: '1/f = 1/v + 1/u',
    explanation: 'The mirror formula 1/f = 1/v + 1/u holds true for all spherical mirrors in all positions of the object using Cartesian sign convention.',
    subject: 'Physics',
    topic: 'Light - Reflection and Refraction',
    chapter_reference: 'Chapter 10: Light - Reflection and Refraction',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=10-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is the lens formula relating object distance (u), image distance (v), and focal length (f)?',
    answer: '1/f = 1/v - 1/u',
    explanation: 'For thin spherical lenses, 1/f = 1/v - 1/u. Note the negative sign distinguishing it from the mirror formula.',
    subject: 'Physics',
    topic: 'Light - Reflection and Refraction',
    chapter_reference: 'Chapter 10: Light - Reflection and Refraction',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=10-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is the SI unit of power of a lens?',
    answer: 'Dioptre (D)',
    explanation: 'Power of a lens P = 1/f (in meters). 1 Dioptre is the power of a lens of focal length 1 metre.',
    subject: 'Physics',
    topic: 'Light - Reflection and Refraction',
    chapter_reference: 'Chapter 10: Light - Reflection and Refraction',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=10-16 (NCERT Class 10 Science)',
  },
  {
    question: 'Which defect of vision is corrected using a concave lens?',
    answer: 'Myopia (Short-sightedness)',
    explanation: 'In myopia, the image is formed in front of the retina. A diverging (concave) lens with appropriate power brings the image back onto the retina.',
    subject: 'Physics',
    topic: 'The Human Eye and Colourful World',
    chapter_reference: 'Chapter 11: The Human Eye and the Colourful World',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=11-16 (NCERT Class 10 Science)',
  },
  {
    question: 'Why does the sky appear blue on a clear day?',
    answer: 'Rayleigh scattering of light (shorter blue wavelengths scatter more by atmospheric molecules)',
    explanation: 'Fine particles in the air scatter blue light (shorter wavelength) more strongly than red light (longer wavelength), causing the blue appearance.',
    subject: 'Physics',
    topic: 'Atmospheric Refraction & Scattering',
    chapter_reference: 'Chapter 11: The Human Eye and the Colourful World',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jesc1=11-16 (NCERT Class 10 Science)',
  },
  {
    question: 'State Ohm’s Law mathematically for a metallic conductor at constant temperature.',
    answer: 'V = I × R (Potential difference is directly proportional to current)',
    explanation: 'Ohm’s law states V ∝ I at constant physical conditions, giving V = IR where R is the resistance of the conductor.',
    subject: 'Physics',
    topic: 'Electricity',
    chapter_reference: 'Chapter 12: Electricity',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=12-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is Joule’s Law of Heating expression for heat produced (H) by current I through resistance R in time t?',
    answer: 'H = I²Rt',
    explanation: 'Heat produced in a resistor is directly proportional to the square of current (I²), resistance (R), and time (t): H = I²Rt.',
    subject: 'Physics',
    topic: 'Heating Effect of Current',
    chapter_reference: 'Chapter 12: Electricity',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=12-16 (NCERT Class 10 Science)',
  },
  {
    question: 'According to Fleming’s Left-Hand Rule, what do the thumb, forefinger, and middle finger represent?',
    answer: 'Thumb: Motion/Force, Forefinger: Magnetic Field, Middle finger: Current (FBI rule)',
    explanation: 'When stretched perpendicularly, Forefinger = Field, Middle finger = Current, Thumb = Force/Motion direction on the conductor.',
    subject: 'Physics',
    topic: 'Magnetic Effects of Electric Current',
    chapter_reference: 'Chapter 13: Magnetic Effects of Electric Current',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=13-16 (NCERT Class 10 Science)',
  },

  // ==========================================
  // CLASS 10 SCIENCE - CHEMISTRY (NCERT Sets)
  // ==========================================
  {
    question: 'What is the chemical formula of Plaster of Paris?',
    answer: 'CaSO₄ · ½H₂O (Calcium sulphate hemihydrate)',
    explanation: 'On heating Gypsum (CaSO₄ · 2H₂O) at 373 K, it loses water molecules and becomes Plaster of Paris (CaSO₄ · ½H₂O).',
    subject: 'Chemistry',
    topic: 'Acids, Bases and Salts',
    chapter_reference: 'Chapter 2: Acids, Bases and Salts',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=2-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is the chemical name and formula of Baking Soda?',
    answer: 'Sodium hydrogen carbonate (NaHCO₃)',
    explanation: 'Baking soda is NaHCO₃, produced using sodium chloride in the Solvay process: NaCl + H₂O + CO₂ + NH₃ → NH₄Cl + NaHCO₃.',
    subject: 'Chemistry',
    topic: 'Acids, Bases and Salts',
    chapter_reference: 'Chapter 2: Acids, Bases and Salts',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=2-16 (NCERT Class 10 Science)',
  },
  {
    question: 'Which metal exists in liquid state at room temperature?',
    answer: 'Mercury (Hg)',
    explanation: 'Mercury is the only metallic element that is liquid at standard room temperature and pressure.',
    subject: 'Chemistry',
    topic: 'Metals and Non-metals',
    chapter_reference: 'Chapter 3: Metals and Non-metals',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=3-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is an amphoteric oxide? Give an example.',
    answer: 'Oxides that react with both acids and bases to produce salt and water (e.g., Al₂O₃, ZnO)',
    explanation: 'Aluminium oxide (Al₂O₃) and Zinc oxide (ZnO) show both acidic and basic behavior, neutralizing both acids and bases.',
    subject: 'Chemistry',
    topic: 'Metals and Non-metals',
    chapter_reference: 'Chapter 3: Metals and Non-metals',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?jesc1=3-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What unique property allows carbon to form long chains with other carbon atoms?',
    answer: 'Catenation and Tetravalency',
    explanation: 'Catenation is the unique ability of carbon to form bonds with other carbon atoms, creating extensive branched, cyclic, or linear chains.',
    subject: 'Chemistry',
    topic: 'Carbon and its Compounds',
    chapter_reference: 'Chapter 4: Carbon and its Compounds',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=4-16 (NCERT Class 10 Science)',
  },
  {
    question: 'What is the general molecular formula for Alkanes (saturated hydrocarbons)?',
    answer: 'CₙH₂ₙ₊₂',
    explanation: 'Alkanes have single covalent bonds between carbons and follow CₙH₂ₙ₊₂ (Methane CH₄, Ethane C₂H₆, Propane C₃H₈).',
    subject: 'Chemistry',
    topic: 'Carbon and its Compounds',
    chapter_reference: 'Chapter 4: Carbon and its Compounds',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=4-16 (NCERT Class 10 Science)',
  },

  // ==========================================
  // CLASS 10 SCIENCE - BIOLOGY (NCERT Sets)
  // ==========================================
  {
    question: 'What is the basic functional filtration unit of the human kidney called?',
    answer: 'Nephron',
    explanation: 'Each kidney contains approximately 1 million nephrons, consisting of Bowman’s capsule and glomerulus for blood filtration.',
    subject: 'Biology',
    topic: 'Life Processes - Excretion',
    chapter_reference: 'Chapter 6: Life Processes',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?jesc1=6-16 (NCERT Class 10 Science)',
  },
  {
    question: 'Which enzyme present in saliva breaks down complex starch into simple sugars?',
    answer: 'Salivary Amylase (Ptyalin)',
    explanation: 'Saliva contains salivary amylase, which hydrolyzes starch into maltose at an optimum pH of around 6.8.',
    subject: 'Biology',
    topic: 'Life Processes - Nutrition',
    chapter_reference: 'Chapter 6: Life Processes',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=6-16 (NCERT Class 10 Science)',
  },
  {
    question: 'Which plant hormone is responsible for the ripening of fruits and promotion of senescence?',
    answer: 'Ethylene',
    explanation: 'Ethylene is a gaseous phytohormone that promotes fruit ripening, while Auxins promote cell elongation and Abscisic acid causes stomata closure.',
    subject: 'Biology',
    topic: 'Control and Coordination',
    chapter_reference: 'Chapter 7: Control and Coordination',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.96,
    source: 'https://ncert.nic.in/textbook.php?jesc1=7-16 (NCERT Class 10 Science)',
  },
  {
    question: 'In Mendel’s dihybrid cross, what is the phenotypic ratio in the F₂ generation?',
    answer: '9 : 3 : 3 : 1',
    explanation: 'Crossing round-yellow with wrinkled-green seeds gives a 9 (Round Yellow) : 3 (Round Green) : 3 (Wrinkled Yellow) : 1 (Wrinkled Green) phenotypic ratio.',
    subject: 'Biology',
    topic: 'Heredity and Evolution',
    chapter_reference: 'Chapter 9: Heredity and Evolution',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'medium',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=9-16 (NCERT Class 10 Science)',
  },
  {
    question: 'According to Lindeman’s 10% law of energy transfer in an ecosystem, how much energy is transferred from one trophic level to the next?',
    answer: 'Only 10% of energy is transferred to the next trophic level',
    explanation: 'Roughly 90% of energy is lost as metabolic heat, respiration, and waste at each level; only 10% becomes biomass for the next consumer.',
    subject: 'Biology',
    topic: 'Our Environment',
    chapter_reference: 'Chapter 15: Our Environment',
    curriculum: 'NCERT',
    class_level: 10,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?jesc1=15-16 (NCERT Class 10 Science)',
  },

  // ==========================================
  // CLASS 9 NCERT CURRICULUM QUESTIONS
  // ==========================================
  {
    question: 'What is the value of Universal Gravitational Constant (G)?',
    answer: '6.674 × 10⁻¹¹ N·m²/kg²',
    explanation: 'Discovered by Henry Cavendish, G = 6.674 × 10⁻¹¹ N·m²/kg² is a fundamental constant in Newton’s Law of Universal Gravitation.',
    subject: 'Physics',
    topic: 'Gravitation',
    chapter_reference: 'Chapter 10: Gravitation',
    curriculum: 'NCERT',
    class_level: 9,
    difficulty: 'medium',
    quality_score: 0.97,
    source: 'https://ncert.nic.in/textbook.php?iesc1=10-15 (NCERT Class 9 Science)',
  },
  {
    question: 'State Newton’s First Law of Motion (Law of Inertia).',
    answer: 'An object remains in a state of rest or uniform motion unless compelled to change that state by an external unbalanced force.',
    explanation: 'Newton’s first law defines inertia, the inherent tendency of objects to resist any change in their velocity.',
    subject: 'Physics',
    topic: 'Force and Laws of Motion',
    chapter_reference: 'Chapter 9: Force and Laws of Motion',
    curriculum: 'NCERT',
    class_level: 9,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?iesc1=9-15 (NCERT Class 9 Science)',
  },
  {
    question: 'What is the difference between speed and velocity?',
    answer: 'Speed is a scalar quantity (magnitude only), while velocity is a vector quantity (magnitude and direction).',
    explanation: 'Velocity specifies how fast an object moves and in which direction (v = displacement / time).',
    subject: 'Physics',
    topic: 'Motion',
    chapter_reference: 'Chapter 8: Motion',
    curriculum: 'NCERT',
    class_level: 9,
    difficulty: 'basic',
    quality_score: 0.98,
    source: 'https://ncert.nic.in/textbook.php?iesc1=8-15 (NCERT Class 9 Science)',
  },
  {
    question: 'State the Law of Conservation of Mass proposed by Antoine Lavoisier.',
    answer: 'Mass can neither be created nor destroyed in a chemical reaction.',
    explanation: 'Total mass of reactants equals the total mass of products in any closed chemical reaction.',
    subject: 'Chemistry',
    topic: 'Atoms and Molecules',
    chapter_reference: 'Chapter 3: Atoms and Molecules',
    curriculum: 'NCERT',
    class_level: 9,
    difficulty: 'basic',
    quality_score: 0.99,
    source: 'https://ncert.nic.in/textbook.php?iesc1=3-15 (NCERT Class 9 Science)',
  },
];

async function seed() {
  console.log(`Starting insertion of ${ncertQuestions.length} NCERT e-book curriculum questions into 'education'...`);
  
  const { data: insData, error: insErr } = await supabase.from('education').insert(ncertQuestions);
  if (insErr) {
    console.error('Insert error:', insErr.message);
  } else {
    console.log(`Successfully inserted ${ncertQuestions.length} NCERT questions!`);
  }

  // Verify total count
  const { count } = await supabase.from('education').select('*', { count: 'exact', head: true });
  console.log(`Total live questions in Supabase 'education' table now: ${count}`);
}

seed();
